@host = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaG9pIiwiYXV0aCI6IkFETUlOIiwiZXhwIjoxNzU3ODQ4MTkxfQ.qIREkMZSzQwK-Miz0jGGT8oBxwnAoxYAotJ2d2TVRiU
@memberId = 1

### 회원 생성
POST {{host}}/api/member/v1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userName": "user2",
  "password": "123456",
  "mobile": "01099998888"
}

### 회원 단건 조회
GET {{host}}/api/member/v1/{{memberId}}
Authorization: Bearer {{token}}

### 회원 검색 조회
@keyword = user
GET {{host}}/api/member/v1?keyword={{keyword}}
Authorization: Bearer {{token}}

### 회원 수정
PUT {{host}}/api/member/v1/{{memberId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userName": "choi",
  "mobile": "01012345678"
}

### 회원 삭제
@deleteMemberId = 2
DELETE {{host}}/api/member/v1/{{deleteMemberId}}
Authorization: Bearer {{token}}
