@host = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTAxMjM0NTY3OCIsImF1dGgiOiJbdGVtcGxhdGUuY2hvaS5qYXZhX3NwcmluZ19jbGVhbl9hcmNpLmluZnJhc3RydWN0dXJlLnNlY3VyaXR5LnByaW5jaXBhbC5QcmluY2lwYWxEZXRhaWxzJCRMYW1iZGEvMHgwMDAwMDI2YTk3ODk5Yjc4QDdhMGViMzVkXSIsImV4cCI6MTc1NzgzNzA5OX0.yoPZiBC36mML--q7s_w_T8tdDqTJfhZokSEMRr0tlLc
@memberId = 1

### 회원 생성
POST {{host}}/api/member/v1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userName": "user1",
  "password": "123456",
  "mobile": "01099998888"
}

### 회원 단건 조회
GET {{host}}/api/member/v1/{{memberId}}
Authorization: Bearer {{token}}

### 회원 전체 조회
GET {{host}}/api/member/v1
Authorization: Bearer {{token}}

### 회원 수정
PUT {{host}}/api/member/v1/{{memberId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userName": "choi",
  "mobile": "01012345678"
}

### 회원 삭제
@deleteMemberId = 2
DELETE {{host}}/api/member/v1/{{deleteMemberId}}
Authorization: Bearer {{token}}
